// ConversationStarters.swift
// 30 Playful, High-Energy, Confidence-Building Starters (Fun only!)
let conversationStarters: [String] = [
    "If we were a power couple in a movie, what would our theme song be?",
    "Quick: give me your best villain laugh — then kiss me before I escape.",
    "What’s the most ridiculous thing we should do before we’re 80?",
    "You just won a lifetime supply of kisses — how are you spending them?",
    "If we opened a bar together, what’s our signature drink called?",
    "Tease me: what’s one thing I do that secretly drives you wild?",
    "Let’s invent a secret handshake right now — go!",
    "What’s the cheesiest pickup line that would 100% work on you?",
    "If we had a couple superpower, what would it be?",
    "Describe our next spontaneous adventure in 5 words.",
    "Rate my outfit out of 10… but you have to flirt while doing it.",
    "What’s the most fun trouble we’ve ever gotten into together?",
    "You’re my celebrity crush for the day — what’s your red-carpet pose?",
    "If we made a TikTok duet right now, what song are we lip-syncing?",
    "Quick compliment battle: you go first, make it bold.",
    "What’s the funniest inside joke we should create tonight?",
    "If we were spies, what would our code names be?",
    "You just became a genie for 10 minutes — what three wishes do I get?",
    "What’s the most playful nickname you’ve ever wanted to give me?",
    "Let’s plan the most ridiculous date ever — money no object.",
    "What emoji combo perfectly describes how you feel about me right now?",
    "Give me your best slow-motion hair flip and strut.",
    "If we started a band tomorrow, what’s our first hit single called?",
    "You’re stuck on a desert island with me — first thing we do?",
    "What’s the sexiest accent you can pull off for 10 seconds?",
    "Quick: roast me in the most charming way possible.",
    "If we were cartoon characters, who would voice us?",
    "What’s the most spontaneous thing we’ve ever done — let’s top it.",
    "You just won me in an auction — what do you do with your prize?",
    "Let’s make up a ridiculous couple hashtag right now."
]
