let deepQuestions: [String] = [
    "When do you feel most alive and electric when we’re together?",
    "What’s one moment with me that still gives you butterflies?",
    "When have you felt the most proud to have me by your side?",
    "What’s a dream we haven’t said out loud yet?",
    "What’s something I do that makes you feel like the luckiest person alive?",
    "When do you feel the most irresistible version of yourself with me?",
    "What’s a fantasy adventure we should absolutely make real?",
    "What song lyric perfectly describes how you feel about us?",
    "When was the last time I made your heart race?",
    "What’s one thing you love about us that no one else sees?",
    "If we wrote a book about our love story, what’s chapter one called?",
    "What’s the boldest thing you’ve ever wanted to whisper to me?",
    "When do you feel the most turned on by who we are together?",
    "What’s a secret talent of yours I need to experience soon?",
    "What’s one way I make you feel completely unstoppable?",
    "If we could freeze one perfect moment forever, which would it be?",
    "What’s something playful you’ve always wanted to try in bed?",
    "When do you feel the most free to be your full, wild self with me?",
    "What’s a compliment you’re dying to give me right now?",
    "What’s the sexiest memory we’ve made so far?",
    "What’s one thing you love that I bring out in you?",
    "When do you feel the most adored and desired by me?",
    "What’s a future memory we haven’t created yet that excites you?",
    "What’s the most romantic risk you’d take for us?",
    "How has loving me made you feel more powerful?",
    "What’s one look I give you that instantly melts you?",
    "When do you feel the most playful and turned on at the same time?",
    "What’s a dream date you’ve never told anyone — until now?", // replaced
    "What’s something I do that makes you grin like an idiot?", // replaced
    "How do you want to be kissed tonight?" // replaced
]
