// MiniLoveActions.swift
// 30 Instant Charismatic Mini Actions (10-second confidence bombs)
let miniLoveActions: [String] = [
    "Wink + mouth ‘You’re in trouble tonight’ across the room.",
    "Send: ‘Thinking about your lips on mine right now.’",
    "Walk past, lightly smack their butt, keep walking.",
    "Hold eye contact 5 seconds longer than normal — smirk.",
    "Text: ‘You + me + no clothes = later.’",
    "Bite your lip while looking at them.",
    "Send a shirtless/selfie with just the caption ‘Yours.’",
    "Trace a heart on their lower back with one finger.",
    "Whisper ‘I want you’ as you pass by.",
    "Send a voice note of just heavy breathing + their name.",
    "Kiss their neck from behind — no explanation.",
    "Text: ‘Cancel whatever you’re doing at 10pm.’",
    "Pull them in by the waist for a 5-second hug.",
    "Send a close-up photo of your lips + ‘These miss you.’",
    "Playfully pin them against the wall for 3 seconds.",
    "Text: ‘I dare you to kiss me when you see this.’",
    "Run your fingers slowly down their arm — stare.",
    "Send: ‘You’ve been warned.’",
    "Kiss their hand like royalty — then bite it softly.",
    "Text a single peach emoji + devil emoji.",
    "Walk by and whisper ‘Tonight you’re mine.’",
    "Send a mirror selfie flexing with ‘For your eyes only.’",
    "Grab their hand, put it on your heart, say ‘Feel that?’",
    "Text: ‘I’m already undressing you in my head.’",
    "Blow them a kiss — then mouth ‘More later.’",
    "Send: ‘Count the minutes until I get my hands on you.’",
    "Spin them into a surprise kiss.",
    "Text: ‘You + me + zero clothes = countdown started.’",
    "Smirk and say ‘You have no idea what’s coming.’",
    "End any sentence today with ‘…in bed.’"
]
