// RomanceChallenges.swift
// 30 High-Energy Romance Challenges (Pure fire, zero lameness)
let romanceChallenges: [String] = [
    "Slow-dance in the kitchen right now — no music required.",
    "Leave a trail of kisses from their neck to wherever you want.",
    "Send a voice note describing exactly what you want to do later.",
    "Recreate your first kiss — but make it 10× hotter.",
    "Blindfold them for 60 seconds and tease with just your voice.",
    "Write ‘I want you’ on their body with a marker or lipstick.",
    "Give them a 2-minute massage that ends in a deep kiss.",
    "Challenge: who can make the other blush harder in 30 seconds.",
    "Whisper your favorite dirty memory in their ear — right now.",
    "Send a photo of the body part you want kissed tonight.",
    "Play the ‘3 compliments, each bolder than the last’ game.",
    "Hide a love note somewhere they’ll find during the day.",
    "Pull them in for a kiss mid-sentence — no warning.",
    "Text them a fantasy and say ‘Tonight?’",
    "Stare into their eyes for 20 seconds — no laughing allowed.",
    "Leave a hickey in a place only you’ll see.",
    "Cook dinner wearing only an apron (or less).",
    "Create a 5-second couple handshake that ends in a kiss.",
    "Send ‘I’m not wearing…’ and finish the sentence.",
    "Re-enact your favorite movie kiss scene.",
    "Give them a lap dance — 30 seconds, full confidence.",
    "Write a 3-line love poem on their thigh with a pen.",
    "Bite their lower lip next time you kiss.",
    "Send a playlist called ‘What I want to do to you tonight’",
    "Kiss them like it’s the last time — every time.",
    "Whisper ‘You’re mine’ possessively during a hug.",
    "Challenge: no kissing on the lips until midnight — tease only.",
    "Leave lipstick kisses on the mirror spelling ‘Tonight’",
    "Tell them exactly how you want to be touched tonight.",
    "End the night with ‘Round two starts now.’"
]
